# Generated by Django 3.2.8 on 2021-11-10 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0003_auto_20211110_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='album',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='artist',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='playlist',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='track',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
